### ISSUE TITLE
How can I train the model myself？

### ISSUE THREAD

**Issue by ALein** [matthp/Physionet2018_Challenge_Submission#1]
Hello, is the "extracted datapath" variable in ‘trainmodel.py’ referring to the processed data storage path? If I want to train my own model, can I get this data from you?

**Comment by ALein** [comment]
![image](https://user-images.githubusercontent.com/14013806/67945472-eb164d00-fc19-11e9-9595-eb666d3e9aec.png)
How can I get these two annotation files

**Comment by sdhmdhr123** [comment]
How can I get these two annotation files

> ![image](https://user-images.githubusercontent.com/14013806/67945472-eb164d00-fc19-11e9-9595-eb666d3e9aec.png)
> How can I get these two annotation files

is there a reply for you?  i want the annotation file too...

**Comment by sdhmdhr123** [comment]
> Hello, is the "extracted datapath" variable in ‘trainmodel.py’ referring to the processed data storage path? If I want to train my own model, can I get this data from you?

我下载下来的就有这些数据呀

**Comment by matthp** [comment]
We no longer have the apnea/hypopnea and sleep/wake annotation files that we used. I added the script we used to convert the WFDB .annotation files (ExpandWFDBannotations.py) into the format expected by ExtractAllData.py.

ExpandWFDBannotations.py assigns a sleep/wake class and a apnea/hypopnea binary class to each sample of the 200 Hz signal based on the contained annotation tags.

 These two scripts will then generate the apneaHypopneaAnnotation_ files and the sleepWakeAnnotation_ files.

**Comment by sdhmdhr123** [comment]
> We no longer have the apnea/hypopnea and sleep/wake annotation files that we used. I added the script we used to convert the WFDB .annotation files (ExpandWFDBannotations.py) into the format expected by ExtractAllData.py.
> 
> ExpandWFDBannotations.py assigns a sleep/wake class and a apnea/hypopnea binary class to each sample of the 200 Hz signal based on the contained annotation tags.
> 
> These two scripts will then generate the apneaHypopneaAnnotation_ files and the sleepWakeAnnotation_ files.

thanks a lot
